const batsman = [
  {
    resource: "players",
    id: 2,
    country_id: 52126,
    firstname: "Ahmed",
    lastname: "Shehzad",
    fullname: "Ahmed Shehzad",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/2/2.png",
    dateofbirth: "1991-11-23",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "legbreak",
    position: {
      resource: "positions",
      id: 1,
      name: "Batsman",
    },
    updated_at: "2020-03-31T05:00:31.000000Z",
  },
  {
    resource: "players",
    id: 5,
    country_id: 52126,
    firstname: "Azhar",
    lastname: "Ali",
    fullname: "Azhar Ali",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/5/5.png",
    dateofbirth: "1985-02-19",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "legbreak",
    position: {
      resource: "positions",
      id: 1,
      name: "Batsman",
    },
    updated_at: "2020-04-01T02:28:23.000000Z",
  },
  {
    resource: "players",
    id: 6,
    country_id: 52126,
    firstname: "Fakhar",
    lastname: "Zaman",
    fullname: "Fakhar Zaman",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/6/6.png",
    dateofbirth: "1990-04-10",
    gender: "m",
    battingstyle: "left-hand-bat",
    bowlingstyle: "slow-left-arm-orthodox",
    position: {
      resource: "positions",
      id: 1,
      name: "Batsman",
    },
    updated_at: "2020-04-02T02:22:22.000000Z",
  },
  {
    resource: "players",
    id: 7,
    country_id: 52126,
    firstname: "Imam",
    lastname: "ul Haq",
    fullname: "Imam ul Haq",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/7/7.png",
    dateofbirth: "1995-12-12",
    gender: "m",
    battingstyle: "left-hand-bat",
    bowlingstyle: null,
    position: {
      resource: "positions",
      id: 1,
      name: "Batsman",
    },
    updated_at: "2020-04-02T09:00:48.000000Z",
  },
  {
    resource: "players",
    id: 8,
    country_id: 52126,
    firstname: "Babar",
    lastname: "Azam",
    fullname: "Babar Azam",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/8/8.png",
    dateofbirth: "1994-10-15",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-offbreak",
    position: {
      resource: "positions",
      id: 1,
      name: "Batsman",
    },
    updated_at: "2020-02-23T10:47:44.000000Z",
  },
];

const bowler = [
  {
    resource: "players",
    id: 3,
    country_id: 52126,
    firstname: "Anwar",
    lastname: "Ali",
    fullname: "Anwar Ali",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/3/3.png",
    dateofbirth: "1987-11-25",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 2,
      name: "Bowler",
    },
    updated_at: "2020-12-14T18:58:56.000000Z",
  },
  {
    resource: "players",
    id: 12,
    country_id: 52126,
    firstname: "Yasir",
    lastname: "Shah",
    fullname: "Yasir Shah",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/12/12.png",
    dateofbirth: "1986-05-02",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "legbreak-googly",
    position: {
      resource: "positions",
      id: 2,
      name: "Bowler",
    },
    updated_at: "2020-04-09T05:17:13.000000Z",
  },
  {
    resource: "players",
    id: 15,
    country_id: 52126,
    firstname: "Mohammad",
    lastname: "Abbas",
    fullname: "Mohammad Abbas",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/15/15.png",
    dateofbirth: "1990-03-10",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 2,
      name: "Bowler",
    },
    updated_at: "2020-04-05T06:16:39.000000Z",
  },
  {
    resource: "players",
    id: 16,
    country_id: 52126,
    firstname: "Hasan",
    lastname: "Ali",
    fullname: "Hasan Ali",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/16/16.png",
    dateofbirth: "1994-07-02",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 2,
      name: "Bowler",
    },
    updated_at: "2020-04-02T08:29:31.000000Z",
  },
  {
    resource: "players",
    id: 17,
    country_id: 52126,
    firstname: "Wahab",
    lastname: "Riaz",
    fullname: "Wahab Riaz",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/17/17.png",
    dateofbirth: "1985-06-28",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "left-arm-fast",
    position: {
      resource: "positions",
      id: 2,
      name: "Bowler",
    },
    updated_at: "2020-04-09T04:55:16.000000Z",
  },
];

const keeper = [
  {
    resource: "players",
    id: 4,
    country_id: 52126,
    firstname: "Sarfraz",
    lastname: "Ahmed",
    fullname: "Sarfraz Ahmed",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/4/4.png",
    dateofbirth: "1987-05-22",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-offbreak",
    position: {
      resource: "positions",
      id: 3,
      name: "Wicketkeeper",
    },
    updated_at: "2020-04-07T08:51:02.000000Z",
  },
  {
    resource: "players",
    id: 20,
    country_id: 52126,
    firstname: "Mohammad",
    lastname: "Rizwan",
    fullname: "Mohammad Rizwan",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/20/20.png",
    dateofbirth: "1992-01-01",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: null,
    position: {
      resource: "positions",
      id: 3,
      name: "Wicketkeeper",
    },
    updated_at: "2020-02-23T10:41:51.000000Z",
  },
  {
    resource: "players",
    id: 22,
    country_id: 98,
    firstname: "Tim",
    lastname: "Paine",
    fullname: "Tim Paine",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/22/22.png",
    dateofbirth: "1984-12-08",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 3,
      name: "Wicketkeeper",
    },
    updated_at: "2020-02-06T04:45:12.000000Z",
  },
  {
    resource: "players",
    id: 37,
    country_id: 98,
    firstname: "Alex",
    lastname: "Carey",
    fullname: "Alex Carey",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/5/37.png",
    dateofbirth: "1991-08-27",
    gender: "m",
    battingstyle: "left-hand-bat",
    bowlingstyle: null,
    position: {
      resource: "positions",
      id: 3,
      name: "Wicketkeeper",
    },
    updated_at: "2020-02-06T04:52:45.000000Z",
  },
  {
    resource: "players",
    id: 45,
    country_id: 98,
    firstname: "Ben",
    lastname: "McDermott",
    fullname: "Ben McDermott",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/13/45.png",
    dateofbirth: "1994-12-12",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 3,
      name: "Wicketkeeper",
    },
    updated_at: "2020-02-06T04:50:22.000000Z",
  },
];

const allrounder = [
  {
    resource: "players",
    id: 10,
    country_id: 52126,
    firstname: "Haris",
    lastname: "Sohail",
    fullname: "Haris Sohail",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/10/10.png",
    dateofbirth: "1989-01-09",
    gender: "m",
    battingstyle: "left-hand-bat",
    bowlingstyle: "slow-left-arm-orthodox",
    position: {
      resource: "positions",
      id: 4,
      name: "Allrounder",
    },
    updated_at: "2020-04-02T07:30:27.000000Z",
  },
  {
    resource: "players",
    id: 13,
    country_id: 52126,
    firstname: "Shadab",
    lastname: "Khan",
    fullname: "Shadab Khan",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/13/13.png",
    dateofbirth: "1998-10-04",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "legbreak",
    position: {
      resource: "positions",
      id: 4,
      name: "Allrounder",
    },
    updated_at: "2020-04-07T09:05:03.000000Z",
  },
  {
    resource: "players",
    id: 14,
    country_id: 52126,
    firstname: "Bilal",
    lastname: "Asif",
    fullname: "Bilal Asif",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/14/14.png",
    dateofbirth: "1985-09-24",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-offbreak",
    position: {
      resource: "positions",
      id: 4,
      name: "Allrounder",
    },
    updated_at: "2020-04-01T03:31:48.000000Z",
  },
  {
    resource: "players",
    id: 21,
    country_id: 52126,
    firstname: "Mohammad",
    lastname: "Hafeez",
    fullname: "Mohammad Hafeez",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/21/21.png",
    dateofbirth: "1980-10-17",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-offbreak",
    position: {
      resource: "positions",
      id: 4,
      name: "Allrounder",
    },
    updated_at: "2020-04-05T07:14:20.000000Z",
  },
  {
    resource: "players",
    id: 31,
    country_id: 98,
    firstname: "Mitchell",
    lastname: "Marsh",
    fullname: "Mitchell Marsh",
    image_path: "https://cdn.sportmonks.com/images/cricket/players/31/31.png",
    dateofbirth: "1991-10-20",
    gender: "m",
    battingstyle: "right-hand-bat",
    bowlingstyle: "right-arm-fast-medium",
    position: {
      resource: "positions",
      id: 4,
      name: "Allrounder",
    },
    updated_at: "2020-02-06T04:44:42.000000Z",
  },
];

export { keeper, batsman, bowler, allrounder };
